### ISSUE TITLE
Not Running on Raspberry pi 3

### ISSUE THREAD

**Issue by SparcImagination** [RunasSudo/PBLive#1]
Can someone please guide me on how to run this? I've installed numerous versions of python to no avail.
I get this error constantly:

(venv) root@rpi3:~/PBLive# python -m pblive
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/PBLive/pblive/__main__.py", line 47, in <module>
    for f in os.listdir('data'):
FileNotFoundError: [Errno 2] No such file or directory: 'data'

Please advise

**Comment by gfhuertac** [comment]
Did you create the data folder as a sibling of the README.md file, and added a file such as example.yaml on it?

**Comment by SparcImagination** [comment]
Thank You! sometimes the answer was **written** right in front you :)
